plugins:
  - jekyll-relative-links
theme: jekyll-theme-modernist
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - index.md
title: Renan Rolo
description: 
google_analytics: G-WVHZZFPGZX

